"""
CDC (Change Data Capture) sensor handler.

Polls a per-asset change log table for new events and dispatches them
via the configured stream.  Each sensor maintains its own cursor
(offset) so multiple streams on the same asset are independent.

Auto-generated by the framework when ``change_tracking: true`` is set
on a database asset.  Not intended for manual YAML configuration.
"""

import json
from typing import Callable

import dagster as dg

from framework.backends import get_backend_for_resource
from framework.core.sensors.sensor_registry import sensor_handler
from framework.model.config_models import SensorConfig, SensorType


@sensor_handler(SensorType.cdc)
def handle_cdc_sensor(config: SensorConfig) -> Callable:
    """Build a CDC dispatch sensor from config.

    Expected keys in ``config.config``::

        change_log_table : str    — FQN of the per-asset change log table
        db_resource_key  : str    — Dagster resource key for the DB connection
        stream_resource_key : str — Dagster resource key for the stream dispatcher
        batch_size       : int    — Max events per tick (default 100)
    """
    cdc_cfg = config.config or {}
    change_log_table: str = cdc_cfg["change_log_table"]
    db_resource_key: str = cdc_cfg["db_resource_key"]
    stream_resource_key: str = cdc_cfg["stream_resource_key"]
    batch_size: int = cdc_cfg.get("batch_size", 100)
    asset_name: str = cdc_cfg["asset_name"]
    table_fqn: str = cdc_cfg["table_fqn"]
    topic: str = cdc_cfg.get("topic", f"cdc.{asset_name}")
    backend_type: str = cdc_cfg.get("backend_type", "postgres")
    backend = get_backend_for_resource(backend_type)

    interval = config.trigger.minimum_interval_seconds or 10

    sensor_tags = config.tags or {}

    @dg.sensor(
        name=config.name,
        description=config.description,
        minimum_interval_seconds=interval,
        default_status=dg.DefaultSensorStatus.RUNNING,
        required_resource_keys={db_resource_key, stream_resource_key},
        tags=sensor_tags,
    )
    def cdc_sensor(context: dg.SensorEvaluationContext) -> None:
        last_id = int(context.cursor or "0")

        db = getattr(context.resources, db_resource_key)
        backend.set_connection(db)
        cursor = backend.get_cursor()

        try:
            rows = backend.fetch_pending_changes(
                cursor=cursor,
                change_log_fqn=change_log_table,
                last_id=last_id,
                limit=batch_size,
            )
            db.commit()
        finally:
            backend.close_cursor(cursor)

        if not rows:
            return

        # Dispatch via the configured stream
        dispatcher = getattr(context.resources, stream_resource_key)

        events = [
            {
                "id": row["id"],
                "op": row["op"],
                "pk": row["pk"] if isinstance(row["pk"], dict)
                    else json.loads(row["pk"]),
                "before": row.get("before_data"),
                "after": row.get("after_data"),
                "run_id": row["run_id"],
                "captured_at": str(row["captured_at"]),
            }
            for row in rows
        ]

        # Wrap in an envelope so clients can subscribe by topic
        message = {
            "topic": topic,
            "source": table_fqn,
            "sensor": config.name,
            "tags": sensor_tags,
            "count": len(events),
            "events": events,
        }

        dispatcher.dispatch([message])

        new_cursor = str(rows[-1]["id"])
        context.update_cursor(new_cursor)

        context.log.info(
            f"CDC sensor '{config.name}': dispatched {len(events)} event(s), "
            f"cursor {last_id} → {new_cursor}"
        )

    return cdc_sensor

